
:version:
  :name: tag_config
  :current: 2.0
  :authors: ["Rodolfo Zitellini"]

:model: inventory_item
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "100":
    :master: "0"
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - d
      - :occurrences: "?"
        :browse_inline: true
        :foreign_class: ^0
        :foreign_field: life_dates
        :foreign_alternates: alternate_dates
    - - j
      - :occurrences: "?"
  "245":
    :master: a
    :indicator: "10"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
  "246":
    :master: a
    :indicator: "2#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "260":
    :master: a
    :indicator: "##"
    :occurrences: "+"
    :fields:
    - - a
      - :occurrences: "*"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - e
      - :occurrences: "?"
    - - f
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "500":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
        :browse_helper: application_helper_link_http
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "560":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "593":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - b
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "599":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - b
      - :occurrences: "?" 
  "700":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :relator_code: "4"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - d
      - :occurrences: "?"
        :browse_inline: true
        :foreign_class: ^0
        :foreign_field: life_dates
        :foreign_alternates: alternate_dates
    - - j
      - :occurrences: "?"
    - - "4"
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "710":
    :master: "0"
    :indicator: "2#"
    :occurrences: "*"
    :relator_code: "4"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: corporate_name
    - - b
      - :occurrences: "*"
    - - c
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: place
    - - g
      - :occurrences: "?"
    - - "4"
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "773":
    :master: w
    :indicator: "18"
    :occurrences: "?"
    :foreign_links: false
    :fields:
    - - w
      - :occurrences: "1"
        :foreign_class: Source
        :foreign_field: id
        :zero_padding: "14"
        :browse_helper: application_helper_link_source_id
  "856":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - u
      - :occurrences: "*"
        :browse_helper: application_helper_link_http
    - - x
      - :occurrences: "?"
    - - z
      - :occurrences: "*"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "930":
    :master: "w"
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - "w"
      - :occurrences: "?"
        :foreign_class: Source
        :foreign_field: id
    - - a
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: title
  "931":
    :master: "w"
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - "w"
      - :occurrences: "?"
        :foreign_class: Holding
        :foreign_field: id
    - - a
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: lib_siglum
  "932":
    :master: "w"
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - "w"
      - :occurrences: "?"
        :foreign_class: Work
        :foreign_field: id
    - - a
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: title