--- !map:ActiveSupport::HashWithIndifferentAccess
_default_unknown_labels: true
main_work:
  label: gnd.main_work
variants:
  label: gnd.variants
references:
  label: gnd.references
codes:
  label: gnd.codes
relations:
  label: gnd.relations
control:
  label: gnd.control
unmatched:
  label: gnd.ungrouped
'001':
  label: gnd.rism_id_number
'003':
  label: gnd.control_number_identifier
'005':
  label: gnd.date_time_last_transaction
'024':
  fields:
    '2':
      label: gnd.source_number_code
    a:
      label: gnd.standard_number_code
  label: gnd.other_standard_identifier
'100':
  fields:
    a:
      label: gnd.name
    d:
      label: gnd.years_birth_death
    m:
      label: gnd.scoring_summary
    n:
      label: gnd.opus_thematic_index_number
    p:
      label: gnd.title_part
    r:
      label: gnd.key_or_mode
    t:
      label: gnd.title_of_work
  label: gnd.heading
'130':
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.partial_title
  label: gnd.preferred_title
'382':
  fields:
    a:
      label: gnd.instrument
  label: gnd.instrument
'430':
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.partial_title
  label: gnd.other_work_title
'548':
  fields:
    a:
      label: gnd.time
    i:
      label: gnd.reference_phrase
    w:
      label: gnd.control_subfield
    '4':
      label: gnd.relationship_code
    '9':
      label: gnd.remarks
  label: gnd.time_relationship
'550':
  fields:
    a:
      label: gnd.subject_term
    g:
      label: gnd.identifying_addition
    i:
      label: gnd.relationship_phase
    '0':
      label: gnd.record_idn
    '4':
      label: gnd.relationship_code
    '9':
      label: gnd.remarks
  label: gnd.subject_term_relationship
C+1:
  label: records.c_plus_1
C+2:
  label: records.c_plus_2
C+3:
  label: records.c_plus_3
C+4:
  label: records.c_plus_4
C+5:
  label: records.c_plus_5
C-1:
  label: records.c_minus_1
C-2:
  label: records.c_minus_2
C-3:
  label: records.c_minus_3
C-4:
  label: records.c_minus_4
C-5:
  label: records.c_minus_5
F+1:
  label: records.f_plus_1
F+2:
  label: records.f_plus_2
F+3:
  label: records.f_plus_3
F+4:
  label: records.f_plus_4
F+5:
  label: records.f_plus_5
F-1:
  label: records.f_minus_1
F-2:
  label: records.f_minus_2
F-3:
  label: records.f_minus_3
F-4:
  label: records.f_minus_4_bass
F-5:
  label: records.f_minus_5
G+1:
  label: records.g_plus_1
G+2:
  label: records.g_plus_2
G+3:
  label: records.g_plus_3
G+4:
  label: records.g_plus_4
G+5:
  label: records.g_plus_5
G-1:
  label: records.g_minus_1
G-2:
  label: records.g_minus_2_treble
G-3:
  label: records.g_minus_3
G-4:
  label: records.g_minus_4
G-5:
  label: records.g_minus_5
g-2:
  label: records.g_minus_2_octave

'042':
  label: gnd.cataloging_level

'043':
  fields:
    c:
      label: gnd.country_code
  label: gnd.country_code

'056':
  label: gnd.meaning_in_rism_editor
  fields:
    a:
      label: gnd.meaning_in_rism_editor

'065':
  label: gnd.gnd_systematics
  fields:
    a:
      label: gnd.notation
    "2":
      label: gnd.source_code

'075':
  label: gnd.entity_type
  fields:
    b:
      label: gnd.entity_type
    "2":
      label: gnd.source_code

'079':
  label: gnd.gnd_specific_coding
  fields:
    a:
      label: gnd.dataset_type
    q:
      label: gnd.subcollection_identifier
    u:
      label: gnd.usage_identifier

'100':
  label: gnd.authorized_form
  fields:
    a:
      label: gnd.name
    d:
      label: gnd.birth_and_death_dates
    m:
      label: gnd.instrumentation_hint
    n:
      label: gnd.numerical_identifier
    p:
      label: gnd.part_title
    r:
      label: gnd.key_or_mode
    t:
      label: gnd.work_title

'130':
  label: gnd.preferred_title
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.part_title

'377':
  label: gnd.language
  fields:
    a:
      label: gnd.language_code
    "2":
      label: gnd.source_code

'380':
  label: form_of_work
  fields:
    "0":
      label: gnd.id_of_authority_record
    a:
      label: gnd.form_of_work
    "2":
      label: gnd.source_code

'382':
  label: gnd.instrument
  fields:
    a:
      label: gnd.ensemble
    "0":
      label: gnd.id_of_authority_record
    "2":
      label: gnd.source_code
    v:
      label: gnd.additional_remark
    n:
      label: gnd.numerical_count
    s:
      label: gnd.total_performers

'383':
  label: gnd.numerical_ordering
  fields:
    a:
      label: gnd.numerical_ordering
    b:
      label: gnd.opus_number
    c:
      label: gnd.catalogue_number

'384':
  label: gnd.musical_key
  fields:
    a:
      label: gnd.musical_key

'400':
  label: gnd.variant_name
  fields:
    a:
      label: gnd.composer
    d:
      label: gnd.birth_and_death_dates
    m:
      label: gnd.instrumentation_hint
    n:
      label: gnd.catalogue_number
    r:
      label: gnd.key_or_mode
    t:
      label: gnd.work_title
    p:
      label: gnd.part_title

'430':
  label: gnd.work_relationship
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.part_title

'500':
  label: gnd.relationship
  fields:
    a:
      label: gnd.composer
    d:
      label: gnd.birth_and_death_dates
    e:
      label: gnd.relation_phrase
    "0":
      label: gnd.id_of_authority_record
    "4":
      label: gnd.relation_code
    i:
      label: gnd.english_version
    w:
      label: gnd.control_field
    "9":
      label: gnd.additional_remark
    t:
      label: gnd.work_title
    n:
      label: gnd.numerical_ordering
    p:
      label: gnd.part_title
    r:
      label: gnd.key_or_mode

'530':
  label: gnd.unit_title_relationship
  fields:
    a:
      label: gnd.work_title
    "0":
      label: gnd.id_of_authority_record
    "4":
      label: gnd.relation_code
    i:
      label: gnd.english_version
    w:
      label: gnd.control_field

'548':
  label: gnd.temporal_relationship
  fields:
    a:
      label: gnd.time
    "4":
      label: gnd.historical_relationship_code
    i:
      label: gnd.english_version
    w:
      label: gnd.control_field
    "9":
      label: gnd.additional_remark

'550':
  label: gnd.topical_term
  fields:
    a:
      label: gnd.form_of_work
    g:
      label: gnd.identifying_addition
    i:
      label: gnd.relation_phrase
    "0":
      label: gnd.id_of_authority_record
    "4":
      label: gnd.relation_code
    "9":
      label: gnd.additional_remark

'667':
  label: gnd.editorial_remark
  fields:
    "5":
      label: gnd.institution_using_field
    a:
      label: gnd.editorial_remark

'670':
  label: gnd.source_reference
  fields:
    a:
      label: gnd.source_reference
    b:
      label: gnd.available_information
    u:
      label: gnd.uri

'675':
  label: gnd.negative_source_reference
  fields:
    a:
      label: gnd.source_reference

'678':
  label: gnd.biographical_or_historical_data
  fields:
    b:
      label: gnd.explanatory_text

'912':
  label: gnd.mailbox
  fields:
    a:
      label: gnd.mailbox

'913':
  label: gnd.previous_name_form
  fields:
    a:
      label: gnd.previous_name_form
    i:
      label: gnd.entity_identification_previous_database
    "0":
      label: gnd.record_id
