--- !map:Settings 
force_editor_ordering: true
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"008": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"024": 
  layout: 
    fields:
    - - "0" 
    - - a
    - - "2"
"035": 
  layout: 
    fields: 
    - - a
    - - z
    - - "9"
"040": 
  layout: 
    fields: 
    - - b
      - read_only: true
    - - e
      - read_only: true
    - - "9"
      - read_only: true
    - - a
      - read_only: true
    - - c
      - read_only: true
    - - d
      - read_only: true
"042": 
  layout: 
    fields: 
    - - a
      - read_only: true
"043": 
  layout: 
    fields: 
    - - c
      - editor_partial: subfield_select_codes
        select_label: "Country"
  tag_params:
    codes:
        - "XA-AD"
        - "XA-AL"
        - "XC-DZ"
        - "XA-AT"
        - "XA-AT-2"
        - "XA-AT-3"
        - "XA-AT-4"
        - "XA-AT-5"
        - "XA-AT-6"
        - "XA-AT-7"
        - "XA-AT-9"
        - "XB-AZ"
        - "XB-BD"
        - "XA-BE"
        - "XA-BY"
        - "XA-BA"
        - "XD-BO"
        - "XD-BR"
        - "XA-BG"
        - "XB-KH"
        - "XD-CA"
        - "XD-CL"
        - "XB-CN"
        - "XD-CO"
        - "XD-CR"
        - "XA-HR"
        - "XD-CU"
        - "XA-CZ"
        - "XA-DK"
        - "XD-EC"
        - "XC-EG"
        - "XA-EE"
        - "XA-FI"
        - "XA-FR"
        - "XB-GE"
        - "XC-GH"
        - "XC-GN"
        - "XD-GT"
        - "XA-DE"
        - "XA-DE-BY"
        - "XA-DE-SN"
        - "XA-GR"
        - "XD-HN"
        - "XB-HK"
        - "XA-HU"
        - "XA-IS"
        - "XB-IN"
        - "XB-ID"
        - "XB-IR"
        - "XB-IQ"
        - "XA-IE"
        - "XB-IL"
        - "XA-IT"
        - "XA-IT-32"
        - "XD-JM"
        - "XB-JP"
        - "XB-KR"
        - "XA-LV"
        - "XB-LB"
        - "XA-LI"
        - "XA-LT"
        - "XA-LU"
        - "XA-MC"
        - "XA-MD"
        - "XA-ME"
        - "XA-MT"
        - "XD-MX"
        - "XA-NL"
        - "XE-NZ"
        - "XD-NI"
        - "XA-GB-NIR"
        - "XA-NO"
        - "XB-PK"
        - "XE-PG"
        - "XD-PY"
        - "XD-PE"
        - "XB-PH"
        - "XA-PL"
        - "XA-PT"
        - "XD-PR"
        - "XA-RO"
        - "XA-RS"
        - "XA-RU"
        - "SB-SA"
        - "XB-SA"
        - "XA-SK"
        - "XA-SI"
        - "XC-ZA"
        - "XA-ES"
        - "XA-SE"
        - "XA-CH"
        - "XA-CH-VD"
        - "XA-SM"
        - "XB-SY"
        - "XB-TW"
        - "XB-TJ"
        - "XD-TT"
        - "XB-TR"
        - "XB-TM"
        - "XC-UG"
        - "XA-UA"
        - "XA-GB"
        - "XD-US"
        - "XD-UY"
        - "XB-UZ"
        - "XA-VA"
        - "XD-VE"
        - "XB-VN"
"065": 
  layout: 
    fields:
    - - "2"
      - read_only: true
    - - a
      - read_only: true
"075": 
  layout: 
    fields: 
    - - b
      - read_only: true
    - - "2"
      - read_only: true
"079": 
  layout: 
    fields: 
    - - q
      - read_only: true
    - - u
"100":
  layout: 
    fields: 
    - - t
    - - m
    - - n
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "100r"
  tag_params:
      100r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"130":
  layout: 
    fields: 
    - - a
    - - f
    - - m
    - - n
    - - o
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "130r"
  tag_params:
      130r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"377": 
  layout: 
    fields: 
    - - a
      - editor_partial: subfield_select_codes
        codes_reference: "377a"
    - - "2"
      - read_only: true
        default: "iso639-2b"
  tag_params:
      377a:
      - aar
      - abk
      - ace
      - ach
      - ada
      - ady
      - afa
      - afh
      - afr
      - ain
      - aka
      - akk
      - alb
      - ale
      - alg
      - alt
      - amh
      - ang
      - anp
      - apa
      - ara
      - arc
      - arg
      - arm
      - arn
      - arp
      - art
      - arw
      - asm
      - ast
      - ath
      - aus
      - ava
      - ave
      - awa
      - aym
      - aze
      - bad
      - bai
      - bak
      - bal
      - bam
      - ban
      - baq
      - bas
      - bat
      - bej
      - bel
      - bem
      - ben
      - ber
      - bho
      - bih
      - bik
      - bin
      - bis
      - bla
      - bnt
      - bos
      - bra
      - bre
      - btk
      - bua
      - bug
      - bul
      - bur
      - byn
      - cad
      - cai
      - car
      - cat
      - cau
      - ceb
      - cel
      - cha
      - chb
      - che
      - chg
      - chi
      - chk
      - chm
      - chn
      - cho
      - chp
      - chr
      - chu
      - chv
      - chy
      - cmc
      - cnr
      - cop
      - cor
      - cos
      - cpe
      - cpf
      - cpp
      - cre
      - crh
      - crp
      - csb
      - cus
      - cze
      - dak
      - dan
      - dar
      - day
      - del
      - den
      - dgr
      - din
      - div
      - doi
      - dra
      - dsb
      - dua
      - dum
      - dut
      - dyu
      - dzo
      - efi
      - egy
      - eka
      - elx
      - eng
      - enm
      - epo
      - est
      - ewe
      - ewo
      - fan
      - fao
      - fat
      - fij
      - fil
      - fin
      - fiu
      - fon
      - fre
      - frm
      - fro
      - frr
      - frs
      - fry
      - ful
      - fur
      - gaa
      - gay
      - gba
      - gem
      - geo
      - ger
      - gez
      - gil
      - gla
      - gle
      - glg
      - glv
      - gmh
      - goh
      - gon
      - gor
      - got
      - grb
      - grc
      - gre
      - grn
      - gsw
      - guj
      - gwi
      - hai
      - hat
      - hau
      - haw
      - heb
      - her
      - hil
      - him
      - hin
      - hit
      - hmn
      - hmo
      - hrv
      - hsb
      - hun
      - hup
      - iba
      - ibo
      - ice
      - ido
      - iii
      - ijo
      - iku
      - ile
      - ilo
      - ina
      - inc
      - ind
      - ine
      - inh
      - ipk
      - ira
      - iro
      - ita
      - jav
      - jbo
      - jpn
      - jpr
      - jrb
      - kaa
      - kab
      - kac
      - kal
      - kam
      - kan
      - kar
      - kas
      - kau
      - kaw
      - kaz
      - kbd
      - kha
      - khi
      - khm
      - kho
      - kik
      - kin
      - kir
      - kmb
      - kok
      - kom
      - kon
      - kor
      - kos
      - kpe
      - krc
      - krl
      - kro
      - kru
      - kua
      - kum
      - kur
      - kut
      - lad
      - lah
      - lam
      - lao
      - lat
      - lav
      - lez
      - lim
      - lin
      - lit
      - lol
      - loz
      - ltz
      - lua
      - lub
      - lug
      - lui
      - lun
      - luo
      - lus
      - mac
      - mad
      - mag
      - mah
      - mai
      - mak
      - mal
      - man
      - map
      - mar
      - mas
      - may
      - mdf
      - mdr
      - men
      - mga
      - mic
      - min
      - mis
      - mkh
      - mlg
      - mlt
      - mnc
      - mni
      - mno
      - moh
      - mon
      - mos
      - mul
      - mun
      - mus
      - mwl
      - mwr
      - myn
      - myv
      - nah
      - nai
      - nap
      - nau
      - nav
      - nbl
      - nde
      - ndo
      - nds
      - nep
      - new
      - nia
      - nic
      - niu
      - nno
      - nob
      - nog
      - non
      - nor
      - nqo
      - nso
      - nub
      - nwc
      - nya
      - nym
      - nyn
      - nyo
      - nzi
      - oci
      - oji
      - ori
      - orm
      - osa
      - oss
      - ota
      - oto
      - paa
      - pag
      - pal
      - pam
      - pan
      - pap
      - pau
      - peo
      - per
      - phi
      - phn
      - pli
      - pol
      - pon
      - por
      - pra
      - pro
      - pus
      - qaa-qtz
      - que
      - raj
      - rap
      - rar
      - roa
      - roh
      - rom
      - rum
      - run
      - rup
      - rus
      - sad
      - sag
      - sah
      - sai
      - sal
      - sam
      - san
      - sas
      - sat
      - scn
      - sco
      - sel
      - sem
      - sga
      - sgn
      - shn
      - sid
      - sin
      - sio
      - sit
      - sla
      - slo
      - slv
      - sma
      - sme
      - smi
      - smj
      - smn
      - smo
      - sms
      - sna
      - snd
      - snk
      - sog
      - som
      - son
      - sot
      - spa
      - srd
      - srn
      - srp
      - srr
      - ssa
      - ssw
      - suk
      - sun
      - sus
      - sux
      - swa
      - swe
      - syc
      - syr
      - tah
      - tai
      - tam
      - tat
      - tel
      - tem
      - ter
      - tet
      - tgk
      - tgl
      - tha
      - tig
      - tir
      - tiv
      - tkl
      - tlh
      - tli
      - tmh
      - tog
      - ton
      - tpi
      - tsi
      - tsn
      - tso
      - tuk
      - tum
      - tup
      - tur
      - tut
      - tvl
      - twi
      - tyv
      - udm
      - uga
      - uig
      - ukr
      - umb
      - und
      - urd
      - uzb
      - vai
      - ven
      - vie
      - vol
      - vot
      - wak
      - wal
      - war
      - was
      - wel
      - wen
      - wln
      - wol
      - xal
      - xho
      - yao
      - yap
      - yid
      - yor
      - ypk
      - zap
      - zbl
      - zen
      - zha
      - znd
      - zul
      - zun
      - zxx
      - zza

"380": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_form
        preserve_foreign_value: true
        editor_partial: subfield_secondary #subfield_autocomplete
    - - "2"
      - read_only: true
        default: "gnd"
"382": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_instrument
        preserve_foreign_value: true
        editor_partial: subfield_secondary #subfield_autocomplete
    - - n
    - - s
    - - v
    - - "2"
      - read_only: true
        default: "gnd"
"383": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
"384": 
  layout: 
    fields: 
    - - a
      - editor_partial: subfield_select_codes
        codes_reference: "384r"
  tag_params:
      384r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"400":
  layout: 
    fields:
    - - a
      - type: gnd_work_person
        #preserve_foreign_value: true
        editor_partial: subfield_secondary
    - - d
      - autocomplete_extra: life_dates
    - - t
    - - m
    - - n
    - - o
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "400r"
  tag_params:
        400r:
        - "A"
        - "a"
        - "A|x"
        - "a|x"
        - "A|b"
        - "a|b"
        - "B"
        - "b"
        - "B|b"
        - "b|b"
        - "C"
        - "c"
        - "C|x"
        - "c|x"
        - "C|b"
        - "c|b"
        - "D"
        - "d"
        - "D|x"
        - "d|x"
        - "D|b"
        - "d|b"
        - "E"
        - "e"
        - "E|b"
        - "e|b"
        - "F"
        - "f"
        - "F|x"
        - "f|x"
        - "G"
        - "g"
        - "G|x"
        - "g|x"
        - "G|b"
        - "g|b"
        - "1t"
        - "2t"
        - "3t"
        - "4t"
        - "5t"
        - "6t"
        - "7t"
        - "8t"
        - "9t"
        - "10t"
        - "11t"
        - "12t"
        - "1tt"
        - "2tt"
        - "3tt"
        - "4tt"
        - "5tt"
        - "6tt"
        - "7tt"
        - "8tt"
        - "9tt"
        - "10tt"
        - "11tt"
        - "12tt"
        - "1byz"
        - "2byz"
        - "3byz"
        - "4byz"
        - "5byz"
        - "6byz"
        - "7byz"
        - "8byz"
"430": 
  layout: 
    fields:
    - - a
    - - f
    - - m
    - - n
    - - o
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "430r"
  tag_params:
        430r:
        - "A"
        - "a"
        - "A|x"
        - "a|x"
        - "A|b"
        - "a|b"
        - "B"
        - "b"
        - "B|b"
        - "b|b"
        - "C"
        - "c"
        - "C|x"
        - "c|x"
        - "C|b"
        - "c|b"
        - "D"
        - "d"
        - "D|x"
        - "d|x"
        - "D|b"
        - "d|b"
        - "E"
        - "e"
        - "E|b"
        - "e|b"
        - "F"
        - "f"
        - "F|x"
        - "f|x"
        - "G"
        - "g"
        - "G|x"
        - "g|x"
        - "G|b"
        - "g|b"
        - "1t"
        - "2t"
        - "3t"
        - "4t"
        - "5t"
        - "6t"
        - "7t"
        - "8t"
        - "9t"
        - "10t"
        - "11t"
        - "12t"
        - "1tt"
        - "2tt"
        - "3tt"
        - "4tt"
        - "5tt"
        - "6tt"
        - "7tt"
        - "8tt"
        - "9tt"
        - "10tt"
        - "11tt"
        - "12tt"
        - "1byz"
        - "2byz"
        - "3byz"
        - "4byz"
        - "5byz"
        - "6byz"
        - "7byz"
        - "8byz"
"500": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - t
    - - "a"
      - type: gnd_work_person
        #preserve_foreign_value: true
        editor_partial: subfield_secondary
    - - d
      - autocomplete_extra: life_dates
    - - e
    - - "0"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - i
    - - w
    - - "9"
    - - n
    - - p
    - - r
  tag_params:
    relator_codes:
      - arra
      - aut1
      - auta
      - autf
      - bear
      - chre
      - comp
      - dich
      - druc
      - feie
      - grav
      - hers
      - hrsg
      - illu
      - istm
      - kom1
      - koma
      - kopi
      - kue1
      - kuen
      - libr
      - obpa
      - malr
      - regi
      - saen
      - saml
      - spon
      - spre
      - stif
      - them
      - uebe
      - urhe
      - vbal
      - verr
      - widm
"530": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_title
        preserve_foreign_value: true
        editor_partial: subfield_secondary #subfield_autocomplete
    - - "0"
      - read_only: true
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - i
      - read_only: true
    - - w
      - read_only: true
        default: "r"
    - - "9"
      - default: "v:"
  tag_params:
    relator_codes:
      - anla
      - nach
      - vorg
      - obal
      - obpa
      - rela
      - them
      - vbal
      - vorl
      - werk
"540": 
  layout: 
    fields: 
    - - a
"548": 
  layout: 
    fields: 
    - - a
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - i
      - read_only: true
    - - w
      - read_only: true
    - - "9"
      - default: "v:"
  tag_params:
    relator_codes:
      - datj
      - code: datj
        label: "gnd.datj_erscheinungszeitraum"
      - dats
      - code: dats
        label: "gnd.dats_kompositionszeitraum"
"550": 
  layout: 
    fields: 
    - - a
    - - g
    - - i
    - - '0'
    - - '4'
    - - '9'
"667": 
  layout: 
    fields: 
    - - a
    - - "5"
      - default: "RISM NFDI4Culture"
"670": 
  layout: 
    fields: 
    - - a
    - - b
    - - u
"675": 
  layout: 
    fields: 
    - - a
"678": 
  layout: 
    fields: 
    - - b
"912": 
  layout: 
    fields: 
    - - a
"913": 
  layout: 
    fields: 
    - - a
    - - "0"
    - - i
