--- !map:Settings
client:
  "024":
    tags:
      a: required
  "110":
    tags:
      a: mandatory
  "368":
    tags:
      a: mandatory
  "670":
    tags:
      "0": required
  "856":
    tags:
      "u": required
      "z": required