--- !map:Settings 
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"031":
  layout:
    fields:
    - - u
      - hidden: true
    - - a
      - read_only: true
        default: "1"
        override_admin: true
    - - b
    - - c
    - - d
    - - m
    - - e
    - - t
      - growfield: true
        type: source_031t_solr
        editor_partial: subfield_autocomplete
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "031r"
        no_sort: true
    - - n
      - values:
        - "xF"
        - "xFC"
        - "xFCG"
        - "xFCGD"
        - "xFCGDA"
        - "xFCGDAE"
        - "xFCGDAEB"
        - "bB"
        - "bBE"
        - "bBEA"
        - "bBEAD"
        - "bBEADG"
        - "bBEADGC"
        - "bBEADGCF"
        editor_partial: subfield_autocomplete
    - - o
    - - g
      - editor_partial: subfield_select_codes_grouped
        codes_reference: clef_groups
    - - s
    - - p
      - editor_partial: subfield_pae
    - - q
    - - z
  tag_params:
    031r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
    clef_groups:
      01_modern_clefs:
      - C-1
      - C-2
      - C-3
      - C-4
      - C-5
      - F-1
      - F-2
      - F-3
      - F-4
      - F-5
      - G-1
      - G-2
      - G-3
      - G-4
      - G-5
      - g-2
      02_mensural_clefs:
      - C+1
      - C+2
      - C+3
      - C+4
      - C+5
      - F+1
      - F+2
      - F+3
      - F+4
      - F+5
      - G+1
      - G+2
      - G+3
      - G+4
      - G+5
"040":
  layout:
    fields:
    - - a
      - hidden: true
    - - d
      - hidden: true
    - - b
      - editor_partial: subfield_select_codes
        select_label: "Language"
        codes_reference: "codes"
  tag_params:
    codes:
      - "eng"
      - "fre"
      - "ger"
      - "ita"
      - "por"
      - "spa"
"100":
  new_window: people
  new_window_field: full_name_equals
  layout:
    fields:
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
  tag_params:
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Misattributed"
"240":
  new_window: standard_titles
  new_window_field: title_equals
  layout:
    fields:
    - - a
      - type: standard_title_no_730
        editor_partial: subfield_secondary
        allow_new: true
    - - o
      - editor_partial: subfield_select_codes
        codes_reference: "240o"
    - - k
      - editor_partial: subfield_select_codes
        codes_reference: "240k"
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "240r"
        no_sort: true
    - - m
  tag_params:
    240k:
      - "Excerpts"
      - "Sketches"
      - "Fragments"
    240o:
      - "Arr"
    240r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"245":
  layout:
    fields:
    - - a
      - growfield: true
"246":
  layout:
    fields:
    - - a
      - growfield: true
"500": 
  layout: 
    fields: 
    - - a
      - growfield: true
"593": 
  layout: 
    fields: 
    - - a
      - values:
        - Print
        - Print with autograph annotations
        - Print with non-autograph annotations
        - Additional manuscript material
        editor_partial: subfield_select
    - - b
      - values:
        - "Inventory"
        editor_partial: subfield_select
"599": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
      - hidden: true
"650":
  new_window: standard_terms
  new_window_field: term_equals
  layout:
    fields:
    - - a
      - type: standard_term
        editor_partial: subfield_secondary
        allow_new: true
"690":
  new_window: publications
  new_window_field: name_equals
  layout:
    fields:
    - - a
      - type: publication_only_short_name
        editor_partial: subfield_secondary
        allow_new: false
    - - n
"691":
  new_window: publications
  new_window_field: name_equals
  layout:
    fields:
    - - a
      - type: publication_only_short_name
        editor_partial: subfield_secondary
        allow_new: false
    - - n
"700":
  new_window: people
  new_window_field: full_name_equals
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - fmo
      - scr
      - cmp
      - prf
      - dte
      - trl
      - edt
      - ltg
      - egr
      - ill
      - prt
      - ppm
      - oth
      - asn
      - arr
"710":
  new_window: institutions
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - c
      - type: place
        editor_partial: subfield_autocomplete
        autocomplete_extra: place
    - - g
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - fmo
      - dpt
      - dte
      - prf
      - bsl
      - evp
      - oth
      - ppm
      - prt
      - asn
"773":
  layout: 
    fields: 
    - - w
      - read_only: true
"775":
  new_window: inventory_items
  layout:
    fields:
    - - w
      - type: inventory_item
        editor_partial: subfield_secondary
        only_new_window: true
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    relator_codes: 
    - led
    - "1st"
"786":
  layout: 
    fields: 
    - - a
    - - d
    - - i
    - - n
    - - o
    - - t
"787":
  new_window: sources
  layout:
    fields:
    - - "4"
      - editor_partial: subfield_select_codes
        codes_reference: "relator_codes"
    - - n
    - - w
      - type: source
        editor_partial: subfield_secondary
  tag_params:
      relator_codes:
      - "rdau:P60191"
      - "rdau:P60198"
      - "rdau:P60311"
      - "rdau:P60195"
      - "rdau:P60242"
      - "rdau:P60194"
"852":
  layout: 
    fields: 
    - - a
    - - d
    - - p
"856": 
  layout: 
    fields: 
    - - u
    - - z
    - - x
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
  tag_params: 
    codes:
      - "IIIF manifest (digitized source)"
      - "IIIF manifest (other)"
      - "Digitized"
      - "Other"
"930":
  new_window: sources
  layout:
    fields:
    - - a
      - type: source
        editor_partial: subfield_secondary
        allow_new: false
        only_new_window: true
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Identification status"
        codes_reference: "codes"
  tag_params: 
    codes:
      - "Identified"
      - "Possibly identified"
"931":
  new_window: holdings
  layout:
    fields:
    - - a
      - type: holding
        editor_partial: subfield_secondary
        allow_new: false
        only_new_window: true
"932":
  new_window: works
  layout:
    fields:
    - - a
      - type: work
        editor_partial: subfield_secondary
        allow_new: false
        only_new_window: true
ui: 
  hide_marc_identifiers: true
triggers:
  - reindex_source
